### ISSUE TITLE
Mapping scripts

### ISSUE THREAD

**Issue by AminaLEM** [novoalab/yeast_RNA_Mod#1]
Hi, 
Please, can you provide the preprocessing scripts just to reproduce the analysis ?
Thanks!

**Comment by enovoa** [comment]
hi, can you be more specific?

**Comment by AminaLEM** [comment]
Hi,
I mean the scripts for the mapping algorithms and parameters part as you referred in the paper Begik et al. 2021

Thanks

**Comment by enovoa** [comment]
Hi @AminaLEM, the mapping parameters and algorithms are described with detail in the Methods section of the paper, please take a look there, thanks
